// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjWmMu7TTiflK9mqe9-qvRtWgw4l9j2U',
    appId: '1:37415732660:web:25f40db5cb4231f3629ee1',
    messagingSenderId: '37415732660',
    projectId: 'purrfectmatch-ef1b7',
    authDomain: 'purrfectmatch-ef1b7.firebaseapp.com',
    storageBucket: 'purrfectmatch-ef1b7.appspot.com',
    measurementId: 'G-6Q77TQ3L24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhXDDndC9X_uo3onHDkBIgly5-00jLpA',
    appId: '1:37415732660:android:a1940b68a213721e629ee1',
    messagingSenderId: '37415732660',
    projectId: 'purrfectmatch-ef1b7',
    storageBucket: 'purrfectmatch-ef1b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJQwXUy8fjTitpoWTKPYlcn1JnXYI_wdk',
    appId: '1:37415732660:ios:fe12647c8eb908ba629ee1',
    messagingSenderId: '37415732660',
    projectId: 'purrfectmatch-ef1b7',
    storageBucket: 'purrfectmatch-ef1b7.appspot.com',
    iosBundleId: 'com.example.catTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJQwXUy8fjTitpoWTKPYlcn1JnXYI_wdk',
    appId: '1:37415732660:ios:2e76ee521963f09f629ee1',
    messagingSenderId: '37415732660',
    projectId: 'purrfectmatch-ef1b7',
    storageBucket: 'purrfectmatch-ef1b7.appspot.com',
    iosBundleId: 'com.example.catTinder.RunnerTests',
  );
}
